Repository mila-aia/image_classification_simulation, pull requests merged in 2022-07, with the labels that each got.

#29 Refactoring ViT baseline and adding subclass of Office31 loader for ViT preproc
  examples/vit/config.yaml
  image_classification_simulation/data/office31_loader.py
  image_classification_simulation/data/utils.py
  image_classification_simulation/models/vit_baseline.py
Labels: bug

#36 Small updates CNN and ViT baselines for MLFlow logs
  examples/vit/config.yaml
  image_classification_simulation/models/classic_cnn_baseline.py
  image_classification_simulation/models/vit_baseline.py
Labels: refactoring

#39 Improvements AutoEncoder baseline
  examples/conv_ae/config.yaml
  image_classification_simulation/models/autoencoder_baseline.py
  image_classification_simulation/models/optim.py
  notebooks/.DS_Store
  notebooks/autoencoder_exp.ipynb
Labels: enhancement

#40 Adding extensive data aug. strategy to Office31
  examples/vit/config.yaml
  image_classification_simulation/data/office31_loader.py
  notebooks/data_aug.ipynb
  notebooks/simple_cnn_baseline.ipynb
Labels: enhancement

#49 Clustering
  image_classification_simulation/image_search.py
  image_classification_simulation/models/clustering.py
  image_classification_simulation/models/clustering_tools.py
Labels: bug, enhancement

#52 Resolving issue #51 on AE bottleneck size
  examples/conv_ae/config.yaml
  image_classification_simulation/models/autoencoder_baseline.py
  notebooks/autoencoder_exp.ipynb
Labels: enhancement

#53 Clustering
  image_classification_simulation/image_search.py
  image_classification_simulation/models/clustering_tools.py
  notebooks/image_similarity_search.ipynb
Labels: enhancement

#50 Readme iteration 1.0
  README.md
  docs/figures/fig0.jpg
Labels: documentation

#60 Clustering
  config/hooks/pre-commit
  image_classification_simulation/data/fsl_sampler.py
  image_classification_simulation/data/office31_loader.py
  image_classification_simulation/data/samplers.py
  image_classification_simulation/data/utils.py
  image_classification_simulation/image_search.py
  image_classification_simulation/models/clustering.py
  image_classification_simulation/models/clustering_tools.py
  notebooks/image_similarity_search.ipynb
  notebooks/transfer_learning.ipynb
  notebooks/vit_testing.ipynb
  requirements.txt
  setup.py
Labels: bug, enhancement
